default: &sqlite3
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *sqlite3
  database: db/team_dashboard_development.sqlite3

test:
  <<: *sqlite3
  database: db/team_dashboard_test.sqlite3

production:
  <<: *sqlite3
  database: db/team_dashboard_production.sqlite3
